#!groovy

// Generated by IBM TransformationAdvisor
// Mon Mar 18 00:52:12 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'daytrader3'
    mvnCommands = '--version'
    test='false'
}